/**
 * Conteúdo DEMO. Tudo fictício e marcado. Caminhos de imagem seguem o pacote de imagens
 * definido em docs/PACOTE_IMAGENS.md (arquivos em public/images/...).
 */
const img = (p: string) => `/images/${p}`;
const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 86_400_000);
const H = (open: string, close: string) => [{ open, close }];

export const seedData = {
  settings: {
    id: 1,
    name: "Academia Demo VireMarca",
    slogan: "Treine forte. Evolua de verdade.",
    logoLightUrl: "/brand/logo-light.svg",
    logoDarkUrl: "/brand/logo-dark.svg",
    monogramUrl: "/brand/monogram.svg",
    accentColor: "#C6FF00",
    whatsapp: "+5500000000000",
    whatsappMessage: "Olá! Vim pelo site e quero saber mais sobre a academia. (DEMO)",
    phone: "(00) 00000-0000",
    email: "contato@exemplo.com",
    address: {
      street: "Rua Exemplo",
      number: "000",
      district: "Bairro Demo",
      city: "Cidade Demo",
      state: "SC",
      zip: "00000-000",
    },
    mapEmbedUrl: null,
    openingHours: {
      mon: H("05:30", "23:00"),
      tue: H("05:30", "23:00"),
      wed: H("05:30", "23:00"),
      thu: H("05:30", "23:00"),
      fri: H("05:30", "22:00"),
      sat: H("08:00", "18:00"),
      sun: H("08:00", "13:00"),
    },
    notice: null,
    social: { instagram: "https://instagram.com/exemplo" },
    legalName: null,
    cnpj: null,
    consentTextVersion: "v1",
    seoTitle: "Academia Demo VireMarca · Musculação, Funcional e Cross",
    seoDescription:
      "Template de academia VireMarca: planos, horários, modalidades e aula experimental grátis. Conteúdo demonstrativo.",
    seoRegion: "Cidade Demo - SC",
    isDemo: true,
  },
  homeSections: [
    ["hero", null],
    ["stats", null],
    ["modalities", "Modalidades"],
    ["schedule", "Grade de horários"],
    ["plans", "Planos"],
    ["trial", "Aula experimental grátis"],
    ["instructors", "Equipe"],
    ["gallery", "Estrutura"],
    ["posts", "Publicações"],
    ["testimonials", "Quem treina aqui"],
    ["faq", "Perguntas frequentes"],
    ["location", "Onde estamos"],
    ["aggregators", null],
  ].map(([key, title], i) => ({ key: key as string, title, sortOrder: i + 1 })),
  heroSlides: [
    {
      title: "Treine como se fosse o dia da prova.",
      subtitle: "Estrutura completa, equipe presente e treino com método.",
      ctaLabel: "Agendar aula grátis",
      ctaHref: "/aula-experimental",
      imageDesktopUrl: img("hero/hero-01-desktop.webp"),
      imageMobileUrl: img("hero/hero-01-mobile.webp"),
      imageAlt: "Atleta realizando levantamento com barra em ambiente escuro",
      sortOrder: 1,
    },
    {
      title: "Força que aparece no espelho e no dia a dia.",
      subtitle: "Musculação orientada do iniciante ao avançado.",
      ctaLabel: "Ver planos",
      ctaHref: "/planos",
      imageDesktopUrl: img("hero/hero-02-desktop.webp"),
      imageMobileUrl: img("hero/hero-02-mobile.webp"),
      imageAlt: "Treino de musculação com halteres sob luz lateral",
      sortOrder: 2,
    },
    {
      title: "Aulas coletivas com energia de verdade.",
      subtitle: "Funcional, cross, HIIT e mais — confira a grade.",
      ctaLabel: "Ver horários",
      ctaHref: "/horarios",
      imageDesktopUrl: img("hero/hero-03-desktop.webp"),
      imageMobileUrl: img("hero/hero-03-mobile.webp"),
      imageAlt: "Grupo em aula de treino funcional",
      sortOrder: 3,
    },
  ],
  stats: [
    { value: "18", suffix: "h", label: "abertos por dia (demo)", sortOrder: 1 },
    { value: "6", suffix: null, label: "modalidades", sortOrder: 2 },
    { value: "40", suffix: "+", label: "aulas por semana (demo)", sortOrder: 3 },
    { value: "1", suffix: "ª", label: "aula grátis", sortOrder: 4 },
  ],
  modalities: [
    {
      name: "Musculação",
      slug: "musculacao",
      summary: "Força e hipertrofia com acompanhamento.",
      level: "todos" as const,
      durationMin: 60,
      imageUrl: img("modalidades/musculacao.webp"),
      imageAlt: "Área de musculação",
      sortOrder: 1,
    },
    {
      name: "Funcional",
      slug: "funcional",
      summary: "Movimentos do dia a dia com intensidade.",
      level: "todos" as const,
      durationMin: 50,
      imageUrl: img("modalidades/funcional.webp"),
      imageAlt: "Treino funcional com kettlebell",
      sortOrder: 2,
    },
    {
      name: "Cross Training",
      slug: "cross-training",
      summary: "Condicionamento de alta intensidade.",
      level: "intermediario" as const,
      durationMin: 60,
      imageUrl: img("modalidades/cross-training.webp"),
      imageAlt: "Treino de cross com barra",
      sortOrder: 3,
    },
    {
      name: "HIIT",
      slug: "hiit",
      summary: "Intervalos curtos, gasto calórico alto.",
      level: "todos" as const,
      durationMin: 40,
      imageUrl: img("modalidades/hiit.webp"),
      imageAlt: "Aula de HIIT",
      sortOrder: 4,
    },
    {
      name: "Lutas",
      slug: "lutas",
      summary: "Técnica, condicionamento e foco.",
      level: "iniciante" as const,
      durationMin: 60,
      imageUrl: img("modalidades/lutas.webp"),
      imageAlt: "Treino de lutas com saco de pancada",
      sortOrder: 5,
    },
    {
      name: "Mobilidade e Alongamento",
      slug: "mobilidade",
      summary: "Movimento melhor para treinar melhor.",
      level: "todos" as const,
      durationMin: 45,
      imageUrl: img("modalidades/mobilidade.webp"),
      imageAlt: "Aula de mobilidade",
      sortOrder: 6,
    },
  ].map((m) => ({
    ...m,
    description: `${m.summary} Conteúdo demonstrativo do template — edite no painel.`,
  })),
  instructors: [1, 2, 3, 4].map((n) => ({
    name: `Professor(a) Demo ${n}`,
    role: ["Head coach", "Musculação", "Coletivas", "Lutas"][n - 1],
    specialties: ["Força e condicionamento", "Hipertrofia", "Funcional e HIIT", "Muay thai"][n - 1],
    bio: "Perfil fictício de demonstração. Substitua pela equipe real no painel.",
    photoUrl: img(`equipe/professor-0${n}.webp`),
    photoAlt: `Foto ilustrativa do professor demo ${n}`,
    professionalRegistry: null,
    sortOrder: n,
  })),
  schedule: [
    ...[1, 2, 3, 4, 5].flatMap((d) => [
      { modality: "funcional", weekday: d, start: "06:30", end: "07:20", room: "Sala 1" },
      { modality: "hiit", weekday: d, start: "12:10", end: "12:50", room: "Sala 1" },
      { modality: "cross-training", weekday: d, start: "18:30", end: "19:30", room: "Box" },
    ]),
    ...[1, 3, 5].map((d) => ({
      modality: "lutas",
      weekday: d,
      start: "20:00",
      end: "21:00",
      room: "Sala 2",
    })),
    ...[2, 4].map((d) => ({
      modality: "mobilidade",
      weekday: d,
      start: "19:40",
      end: "20:25",
      room: "Sala 2",
    })),
    { modality: "funcional", weekday: 6, start: "09:00", end: "09:50", room: "Sala 1" },
  ],
  plans: [
    {
      name: "Mensal",
      period: "mensal" as const,
      priceCents: 14990,
      benefits: ["Musculação livre", "Avaliação inicial", "App de treino (demo)"],
      sortOrder: 1,
      ctaLabel: "Quero o mensal",
    },
    {
      name: "Trimestral",
      period: "trimestral" as const,
      priceCents: 12990,
      installmentsNote: "por mês · 3x",
      benefits: ["Tudo do mensal", "Aulas coletivas", "1 reavaliação"],
      sortOrder: 2,
      highlighted: true,
      badge: "Mais escolhido",
      ctaLabel: "Quero o trimestral",
    },
    {
      name: "Anual",
      period: "anual" as const,
      priceCents: 9990,
      installmentsNote: "por mês · 12x",
      benefits: ["Tudo do trimestral", "Reavaliação trimestral", "Camiseta (demo)"],
      sortOrder: 3,
      ctaLabel: "Quero o anual",
    },
  ],
  gallery: [
    ["Musculação", "estrutura/musculacao.webp"],
    ["Cardio", "estrutura/cardio.webp"],
    ["Funcional", "estrutura/funcional.webp"],
    ["Box de cross", "estrutura/box-cross.webp"],
    ["Sala de lutas", "estrutura/lutas.webp"],
    ["Vestiário", "estrutura/vestiario.webp"],
  ].map(([area, p], i) => ({
    area: area!,
    imageUrl: img(p!),
    imageAlt: `Ambiente ilustrativo: ${area}`,
    caption: "Imagem ilustrativa (demo)",
    isIllustration: true,
    sortOrder: i + 1,
  })),
  categories: [
    { name: "Treino", slug: "treino" },
    { name: "Nutrição", slug: "nutricao" },
    { name: "Novidades", slug: "novidades" },
  ],
  posts: [
    {
      title: "Como montar sua primeira semana de treino",
      slug: "primeira-semana-de-treino",
      excerpt: "Um guia simples para começar sem se machucar.",
      coverUrl: img("blog/post-01.webp"),
      coverAlt: "Pessoa ajustando anilhas na barra",
      status: "published" as const,
      publishedAt: daysAgo(12),
      featured: true,
    },
    {
      title: "Aquecimento: 8 minutos que mudam o treino",
      slug: "aquecimento-8-minutos",
      excerpt: "Por que aquecer e como fazer do jeito certo.",
      coverUrl: img("blog/post-02.webp"),
      coverAlt: "Aquecimento com corda",
      status: "published" as const,
      publishedAt: daysAgo(6),
    },
    {
      title: "Nova grade de aulas coletivas (demo)",
      slug: "nova-grade-aulas",
      excerpt: "Mais horários de funcional e HIIT.",
      coverUrl: img("blog/post-03.webp"),
      coverAlt: "Aula coletiva",
      status: "published" as const,
      publishedAt: daysAgo(2),
    },
  ].map((p) => ({
    ...p,
    tags: ["demo"],
    contentHtml: `<p>${p.excerpt}</p><p>Conteúdo demonstrativo do Template Academia VireMarca. Edite ou apague no painel.</p>`,
  })),
  testimonials: [
    {
      authorName: "Aluno(a) Demo A",
      authorInfo: "Treina há 1 ano",
      quote: "Depoimento fictício de exemplo para o template.",
      rating: 5,
      sortOrder: 1,
    },
    {
      authorName: "Aluno(a) Demo B",
      authorInfo: "Funcional",
      quote: "Texto de exemplo: substitua por depoimentos reais autorizados.",
      rating: 5,
      sortOrder: 2,
    },
    {
      authorName: "Aluno(a) Demo C",
      authorInfo: "Cross Training",
      quote: "Exemplo de depoimento para demonstração do layout.",
      rating: 5,
      sortOrder: 3,
    },
  ].map((t) => ({ ...t, isDemo: true, active: true })),
  faqs: [
    [
      "A primeira aula é grátis?",
      "Sim. Agende pelo site e venha conhecer a estrutura. (Regra demo — ajuste no painel.)",
    ],
    ["Preciso de avaliação física?", "Recomendamos a avaliação inicial, incluída nos planos demo."],
    ["Aceitam Wellhub ou TotalPass?", "Configure no painel quais agregadores a academia aceita."],
    [
      "Qual o horário de funcionamento?",
      "Veja a seção Localização — os horários vêm das Configurações.",
    ],
    ["Posso congelar o plano?", "Política fictícia de exemplo. Defina as regras reais no painel."],
  ].map(([question, answer], i) => ({ question: question!, answer: answer!, sortOrder: i + 1 })),
};
